name: flutter_controle_enderecos
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  encrypt: ^5.0.0
  pointycastle: ^3.6.2
  crypto: ^3.0.6
  pdf: ^3.6.0
  path_provider: ^2.0.8
  fl_chart: ^0.63.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png
